(module
 (type $iii (func (param i32 i32) (result i32)))
 (type $ii (func (param i32) (result i32)))
 (type $v (func))
 (type $FUNCSIG$i (func (result i32)))
 (memory $0 0)
 (table 1 anyfunc)
 (elem (i32.const 0) $null)
 (export "memory" (memory $0))
 (export "table" (table $0))
 (export "f" (func $reexportUser/f))
 (start $start)
 (func $export/add (; 0 ;) (; has Stack IR ;) (type $iii) (param $0 i32) (param $1 i32) (result i32)
  (i32.add
   (get_local $0)
   (get_local $1)
  )
 )
 (func $export/mul (; 1 ;) (; has Stack IR ;) (type $FUNCSIG$i) (result i32)
  (i32.const 12)
 )
 (func $reexportUser/f (; 2 ;) (; has Stack IR ;) (type $ii) (param $0 i32) (result i32)
  (local $1 i32)
  (set_local $1
   (call $export/add
    (call $export/add
     (get_local $0)
     (i32.const 0)
    )
    (i32.const 0)
   )
  )
  (call $export/add
   (get_local $0)
   (get_local $1)
  )
 )
 (func $start (; 3 ;) (; has Stack IR ;) (type $v)
  (drop
   (call $export/add
    (i32.const 1)
    (i32.const 2)
   )
  )
  (drop
   (call $export/mul)
  )
 )
 (func $null (; 4 ;) (; has Stack IR ;) (type $v)
  (nop)
 )
)
